-- Add default categories
INSERT INTO "categories" ("name", "createdAt", "updatedAt")
VALUES
    ('Concerts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sports Events', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Conferences', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Exhibitions', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Festivals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Movies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Theatre', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Volunteering Events', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Training Courses', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Art Shows', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Charity Events', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Product Launches', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Family Events', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Business Events', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 